#### Startup Actions
on-graphic-initialized = {
    { type = "exec", exec = "waybar" }
}


#### Keyboard Settings
keymap =    """
            xkb_options { include "caps:escape,ctrl:swap_lalt_lctl" }
            """

repeat-rate = { rate = 20, delay = 200 }


#### Monitors
[[outputs]]
name = "left"
match.connector = "DP-2"
x = 0
y = 0
mode = { width = 2560, height = 1440, refresh-rate = 179.999 }

[[outputs]]
name = "right"
match.connector = "HDMI-A-1"
x = 2560
y = 360
mode = { width = 1920, height = 1080, refresh-rate = 100.000 }

#### Shortcuts
[shortcuts]

## Workspaces
logo-1          = { type = "show-workspace", name = "1",  output.name = "left"  }
logo-2          = { type = "show-workspace", name = "2",  output.name = "left"  }
logo-3          = { type = "show-workspace", name = "3",  output.name = "left"  }
logo-4          = { type = "show-workspace", name = "4",  output.name = "left"  }
logo-5          = { type = "show-workspace", name = "5",  output.name = "left"  }
logo-6          = { type = "show-workspace", name = "6",  output.name = "right" }
logo-7          = { type = "show-workspace", name = "7",  output.name = "right" }
logo-8          = { type = "show-workspace", name = "8",  output.name = "right" }
logo-9          = { type = "show-workspace", name = "9",  output.name = "right" }
logo-10         = { type = "show-workspace", name = "10", output.name = "right" }

logo-shift-1    = { type = "move-to-output", name = "1",  output.name = "left"  }
logo-shift-2    = { type = "move-to-output", name = "2",  output.name = "left"  }
logo-shift-3    = { type = "move-to-output", name = "3",  output.name = "left"  }
logo-shift-4    = { type = "move-to-output", name = "4",  output.name = "left"  }
logo-shift-5    = { type = "move-to-output", name = "5",  output.name = "left"  }
logo-shift-6    = { type = "move-to-output", name = "6",  output.name = "right" }
logo-shift-7    = { type = "move-to-output", name = "7",  output.name = "right" }
logo-shift-8    = { type = "move-to-output", name = "8",  output.name = "right" }
logo-shift-9    = { type = "move-to-output", name = "9",  output.name = "right" }
logo-shift-10   = { type = "move-to-output", name = "10", output.name = "right" }

## Window Movement
logo-Left               = "focus-left"
logo-Right              = "focus-right"
logo-Up                 = "focus-up"
logo-Down               = "focus-down"

logo-shift-Left         = "move-left"
logo-shift-Right        = "move-right"
logo-shift-Up           = "move-up"
logo-shift-Down         = "move-down"

logo-ctrl-h             = "split-horizontal"
logo-ctrl-v             = "split-vertical"
logo-e                  = "toggle-split"
logo-shift-f            = "toggle-fullscreen"
logo-shift-space        = "toggle-floating"
window-management-key   = "Super_L"

## Launching Apps
logo-Return             = { type = "exec", exec = "wezterm" }
logo-p                  = { type = "exec", exec = ["wofi", "--show", "drun"] }
logo-b                  = { type = "exec", exec = "zen-browser" }
logo-shift-b            = { type = "exec", exec = "google-chrome-stable" }
logo-f                  = { type = "exec", exec = "thunar" }
logo-c                  = { type = "exec", exec = "code" }
logo-s                  = { type = "exec", exec = "spotify" }
logo-d                  = { type = "exec", exec = "discord" }
# logo-shift-p            = { type = "exec", exec = [] }

## System Actions
logo-q                  = "close"
logo-shift-r            = "reload-config-toml"
logo+shift+e            = { type = "exec", exec = "~/.config/jay/exit-menu.sh" }
logo+shift+s            = { type = "exec", exec = "~/.config/jay/shutdown-menu.sh" }


#### Inputs
[[inputs]]
tag = "mice"
match.is-pointer = true
natural-scrolling = true


#### Theme
[theme]
border-width = 2
border-color = "#00FFFF"
